### ISSUE TITLE
Rtsp player

### ISSUE THREAD

**Issue by alesimoes** [adamfisher/Xamarin.Forms.VideoPlayer#106] opened 2018-03-06 18:01 UTC
Hi Adam, great work!

I'm getting error on play rtsp://192.168.1.13:554/onvif1 
java.io.FileNotFoundException: No content provider: rtsp://192.168.1.13:554/onvif1

could you please help me? 

Thanks.

**Comment by adamfisher** [comment] 2018-03-11 04:05
Duplicate of #59

**Closed as completed by adamfisher** 2018-03-11 04:05 UTC
Labels: duplicate, VideoPlayer.Android
