### ISSUE TITLE
How to play the Videos streamed via ASP.NET Core and Authorize attribute?

### ISSUE THREAD

**Issue by pankaj-nikam** [adamfisher/Xamarin.Forms.VideoPlayer#131] opened 2018-07-12 11:40 UTC
Hi there,

I have purchased the license for the player and I wish to know how to play the videos which are protected by the Authorize attribute? I have JWT for authenticating and was wondering if I can use it the videos. Can you please guide?

Thanks
Regards,

Pankaj Nikam

**Comment by adamfisher** [comment] 2018-07-15 13:26
This sounds like a duplicate of https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/issues/79

**Closed as completed by adamfisher** 2018-07-15 13:26 UTC
Labels: duplicate, question

**Comment by adamfisher** [comment] 2018-07-15 13:28
You will need to download the video stream independently of the player and then pass it in either as a stream object or save it locally first and then use `VideoSource.FromFile(...)`.

**Comment by pankaj-nikam** [comment] 2018-07-15 17:16
Hi Adam,
Yes. It may be a duplicate. It has a similar followup question where I would like to consume the file as it starts downloading using the method you mentioned. Can you please put a light on the topic?
Thanks.

Regards,

Pankaj Nikam
