### ISSUE TITLE
ChillPlayer sample doesn't compile on Android

### ISSUE THREAD

**Issue by scastria** [adamfisher/Xamarin.Forms.VideoPlayer#108] opened 2018-03-22 15:28 UTC
/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.Android/obj/Debug/android/manifest/AndroidManifest.xml(0,0): Error APT0000: No resource found that matches the given name (at 'theme' with value '@style/MainTheme'). (APT0000) (ChillPlayer.Android)

**Comment by adamfisher** [comment] 2018-04-22 22:31
Duplicate of #109 and will be tracked there.

**Closed as completed by adamfisher** 2018-04-22 22:31 UTC
Labels: bug, Chill Player

**Comment by adamfisher** [comment] 2018-04-22 22:34
This issue should be resolved now with the latest commit.
