### ISSUE TITLE
Xamarin Forms Android Video Player Error

### ISSUE THREAD

**Issue by hernandoz** [adamfisher/Xamarin.Forms.VideoPlayer#135] opened 2018-08-07 14:27 UTC
Hi , I get this error when I load the page to play the video .

![image](https://user-images.githubusercontent.com/1914468/43781577-22e2f526-9a55-11e8-8570-27cc03a2732e.png)

```
08-07 15:23:17.942 I/mono-stdout(18171): VideoPlayer [INFO]: Creating video player instance [3869b44b-2cd5-411c-ae19-a5320fb08f01]VideoPlayer [INFO]: Creating video player instance [3869b44b-2cd5-411c-ae19-a5320fb08f01]

08-07 15:23:18.022 D/Mono    (18171): Assembly Ref addref Octane.Xamarin.Forms.VideoPlayer.Android[0xb4b88460] -> System[0x983cc220]: 20
08-07 15:23:18.032 W/art     (18171): JNI RegisterNativeMethods: attempt to register 0 native methods for md5887c5a9290fd61a835203058c927117c.VideoPlayerRenderer
08-07 15:23:18.092 D/PhoneWindow(18171): *FMB* installDecor mIsFloating : false
08-07 15:23:18.092 D/PhoneWindow(18171): *FMB* installDecor flags : -2139029246
08-07 15:23:18.162 I/mono-stdout(18171): VideoPlayer [INFO]: Video Source: https://vjs.zencdn.net/v/oceans.mp4VideoPlayer [INFO]: Video Source: https://vjs.zencdn.net/v/oceans.mp4

08-07 15:23:18.252 V/MediaPlayer-JNI(18171): native_setup
08-07 15:23:18.252 V/MediaPlayer(18171): constructor
08-07 15:23:18.262 V/MediaPlayer(18171): setListener
08-07 15:23:18.262 E/MediaPlayer-JNI(18171): QCMediaPlayer mediaplayer NOT present
08-07 15:23:18.262 V/MediaPlayer-JNI(18171): get_session_id()
08-07 15:23:18.272 D/MediaPlayer(18171): setDataSource IOException happend : 
08-07 15:23:18.272 D/MediaPlayer(18171): java.io.FileNotFoundException: No content provider: https://vjs.zencdn.net/v/oceans.mp4
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1117)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:970)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:897)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1112)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.widget.VideoView.openVideo(VideoView.java:376)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.widget.VideoView.access$2100(VideoView.java:73)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.widget.VideoView$7.surfaceCreated(VideoView.java:657)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:709)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1306)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7031)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.Choreographer.doFrame(Choreographer.java:576)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.os.Handler.handleCallback(Handler.java:739)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.os.Looper.loop(Looper.java:145)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at android.app.ActivityThread.main(ActivityThread.java:6914)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at java.lang.reflect.Method.invoke(Native Method)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
08-07 15:23:18.272 D/MediaPlayer(18171): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
08-07 15:23:18.272 D/MediaPlayer(18171): Couldn't open file on client side, trying server side
08-07 15:23:18.272 V/MediaPlayer(18171): setVideoSurfaceTexture
08-07 15:23:18.272 V/MediaPlayer-JNI(18171): setAudioStreamType: 3
08-07 15:23:18.272 V/MediaPlayer(18171): MediaPlayer::setAudioStreamType
08-07 15:23:18.272 V/MediaPlayer(18171): setVideoSurfaceTexture
08-07 15:23:18.272 V/MediaPlayer(18171): prepareAsync
08-07 15:23:18.282 D/MediaHTTPConnection(18171): setReadTimeOut =  30000ms
08-07 15:23:18.292 D/MediaHTTPConnection(18171): setReadTimeout with 30000ms
08-07 15:23:18.292 I/System.out(18171): (HTTPLog)-Static: isSBSettingEnabled false
08-07 15:23:18.292 I/System.out(18171): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:23:18.292 D/AbsSeekBar(18171): AbsSeekBar Constructor: mAllowedSeeBarAnimation = false
08-07 15:23:18.312 D/AndroidRuntime(18171): Shutting down VM
08-07 15:23:18.322 I/System.out(18171): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:23:18.482 V/MediaHTTPConnection(18171): mTotalSize is 23014356
Unhandled Exception:

Java.Lang.NoSuchMethodError: No static method obtainAttributes(Landroid/content/res/Resources;Landroid/content/res/Resources$Theme;Landroid/util/AttributeSet;[I)Landroid/content/res/TypedArray; in class Landroid/support/v4/content/res/TypedArrayUtils; or its super classes (declaration of 'android.support.v4.content.res.TypedArrayUtils' appears in /data/app/com.SRM.Mobile.SiteDiary-1/base.apk)
```

thanks for your help.

Hernando

**Comment by adamfisher** [comment] 2018-08-08 02:02
This sounds like a duplicate of #59

**Comment by hernandoz** [comment] 2018-08-08 09:03
Hi, I fixed the Java error by updating all the NuGet's Packages to latest. But now I am having with my video feed store in Azure Blood storage , it would not play , I tried all the solution on the other post #59 but still now working. 

```
`08-08 09:57:41.633 I/mono-stdout( 5118): VideoPlayer [INFO]: Creating video player instance [8bc9bcf1-447b-4398-8e9e-ba7e9baed19f]VideoPlayer [INFO]: Creating video player instance [8bc9bcf1-447b-4398-8e9e-ba7e9baed19f]

08-08 09:57:41.693 D/PhoneWindow( 5118): *FMB* installDecor mIsFloating : false
08-08 09:57:41.693 D/PhoneWindow( 5118): *FMB* installDecor flags : -2139029246
08-08 09:57:41.703 I/mono-stdout( 5118): VideoPlayer [INFO]: Video Source: https://REMOVE.blob.core.windows.net/REMOVEb6d.mp4
VideoPlayer [INFO]: Video Source: https://*******.blob.core.windows.net/*******/******/*******2-4ac1-a0db-5f3fae7a4b6d.mp4
08-08 09:57:41.753 W/VideoView( 5118): Skip requesting AudioFocus, This package already requested the audio focus
08-08 09:57:41.753 V/MediaPlayer-JNI( 5118): native_setup
08-08 09:57:41.763 V/MediaPlayer( 5118): constructor
08-08 09:57:41.763 V/MediaPlayer( 5118): setListener
08-08 09:57:41.763 E/MediaPlayer-JNI( 5118): QCMediaPlayer mediaplayer NOT present
08-08 09:57:41.763 V/MediaPlayer-JNI( 5118): get_session_id()
08-08 09:57:41.763 D/MediaPlayer( 5118): setDataSource IOException happend : 
08-08 09:57:41.763 D/MediaPlayer( 5118): java.io.FileNotFoundException: No content provider: https://*********.blob.core.windows.net/s*******/******/******-5f3fae7a4b6d.mp4
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1117)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:970)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:897)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1112)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.widget.VideoView.openVideo(VideoView.java:376)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.widget.VideoView.access$2100(VideoView.java:73)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.widget.VideoView$7.surfaceCreated(VideoView.java:657)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:709)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1306)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7031)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.Choreographer.doFrame(Choreographer.java:576)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.os.Handler.handleCallback(Handler.java:739)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.os.Looper.loop(Looper.java:145)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at android.app.ActivityThread.main(ActivityThread.java:6914)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at java.lang.reflect.Method.invoke(Native Method)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
08-08 09:57:41.763 D/MediaPlayer( 5118): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
08-08 09:57:41.763 D/MediaPlayer( 5118): Couldn't open file on client side, trying server side
08-08 09:57:41.773 V/MediaPlayer( 5118): setVideoSurfaceTexture
08-08 09:57:41.783 V/MediaPlayer-JNI( 5118): setAudioStreamType: 3
08-08 09:57:41.783 V/MediaPlayer( 5118): MediaPlayer::setAudioStreamType
08-08 09:57:41.783 V/MediaPlayer( 5118): setVideoSurfaceTexture
08-08 09:57:41.783 V/MediaPlayer( 5118): prepareAsync
08-08 09:57:41.783 D/MediaHTTPConnection( 5118): setReadTimeOut =  30000ms
08-08 09:57:41.783 D/MediaHTTPConnection( 5118): setReadTimeout with 30000ms
08-08 09:57:41.783 I/System.out( 5118): (HTTPLog)-Static: isSBSettingEnabled false
08-08 09:57:41.783 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:41.793 D/AbsSeekBar( 5118): AbsSeekBar Constructor: mAllowedSeeBarAnimation = false
08-08 09:57:41.853 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:42.213 V/MediaHTTPConnection( 5118): mTotalSize is 8364976
08-08 09:57:42.553 D/MediaHTTPConnection( 5118): setReadTimeout with 30000ms
08-08 09:57:42.553 I/System.out( 5118): (HTTPLog)-Static: isSBSettingEnabled false
08-08 09:57:42.553 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:42.553 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:42.933 V/MediaHTTPConnection( 5118): mTotalSize is 8364976
08-08 09:57:42.933 V/MediaHTTPConnection( 5118): Server doesnt support Partial Request
08-08 09:57:42.933 W/MediaHTTPConnection( 5118): readAt 8230507 / 32768 => java.net.ProtocolException
08-08 09:57:42.943 V/MediaHTTPConnection( 5118): Return -EPIPE
08-08 09:57:43.073 D/MediaHTTPConnection( 5118): setReadTimeout with 30000ms
08-08 09:57:43.073 I/System.out( 5118): (HTTPLog)-Static: isSBSettingEnabled false
08-08 09:57:43.083 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:43.083 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:43.413 V/MediaHTTPConnection( 5118): mTotalSize is 8364976
08-08 09:57:43.943 D/MediaHTTPConnection( 5118): setReadTimeout with 30000ms
08-08 09:57:43.943 I/System.out( 5118): (HTTPLog)-Static: isSBSettingEnabled false
08-08 09:57:43.943 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:43.953 I/System.out( 5118): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-08 09:57:44.343 V/MediaHTTPConnection( 5118): mTotalSize is 8364976
08-08 09:57:44.343 V/MediaHTTPConnection( 5118): Server doesnt support Partial Request
08-08 09:57:44.353 W/MediaHTTPConnection( 5118): readAt 8230507 / 32768 => java.net.ProtocolException
08-08 09:57:44.353 V/MediaHTTPConnection( 5118): Return -EPIPE
08-08 09:57:44.383 V/MediaPlayer( 5118): message received msg=100, ext1=1, ext2=-2147483648
08-08 09:57:44.383 E/MediaPlayer( 5118): error (1, -2147483648)
08-08 09:57:44.383 V/MediaPlayer( 5118): callback application
08-08 09:57:44.383 V/MediaPlayer( 5118): back from callback
08-08 09:57:44.383 E/MediaPlayer( 5118): Error (1,-2147483648)
08-08 09:57:44.383 D/VideoView( 5118): Error: 1,-2147483648
08-08 09:57:44.393 I/mono-stdout( 5118): VideoPlayer [ERROR]: Unknown
VideoPlayer [ERROR]: Unknown
```
It seem that the video Player does not support Azure blob Storage ?  

thanks for your help

**Comment by adamfisher** [comment] 2018-08-17 18:08
I know I have heard of people using blob storage successfully. It's just a matter of making sure you passing a vanilla URL with no extra auth/security stuff in place around it which appear you are doing that correctly from what I can tell.

It sounds like nougat or higher version you have to use Content Provider as mentioned in this post with some configuration in your manifest:

https://stackoverflow.com/questions/46080969/mediaplayer-java-io-filenotfoundexception-no-content-provider

**Closed as completed** 2018-08-25 15:20 UTC
Labels: question

**Comment by markdav-is** [comment] 2018-12-29 06:58
we are having this same issue.  do you have an example of creating a content provider for MP4 file on azure blog storage?
