### ISSUE TITLE
Fill Mode Not Working

### ISSUE THREAD

**Issue by brswan** [adamfisher/Xamarin.Forms.VideoPlayer#72] opened 2017-11-13 16:09 UTC
Using the trial currently.

Xamarin Forms v2.4.0.38779
.NET Standard v1.4

Fill Mode on Android and UWP is not working as expected.  Video Player takes up entire screen real estate.  I have tried using the WidthRequest and HeightRequest with but they appear to not work also.

![screenshot_20171113-110128](https://user-images.githubusercontent.com/10222248/32735576-1c9f73a2-c863-11e7-9533-c6c2b1f05002.png)

**Comment by adamfisher** [comment] 2017-11-15 02:34
Duplicate of #3

**Closed as completed by adamfisher** 2017-11-15 02:34 UTC
Labels: VideoPlayer.Android
