### ISSUE TITLE
Video player cuts into half after the device screen rotated in Moto g 2nd Gen (Android : 5.1)

### ISSUE THREAD

**Issue by SudharsanKrishnamoorthy** [adamfisher/Xamarin.Forms.VideoPlayer#77] opened 2017-12-15 06:28 UTC
Hi Adam,
While playing a video in Moto g 2nd gen device using this player, video player cuts into half after the screen is rotated. 

We have tried the below attribute:
"videoPlayer.FillMode = FillMode.ResizeAspectFill"  still no change.

Player works fine in other devices.

Please find the screenshots attached.
![1](https://user-images.githubusercontent.com/20511534/34029536-1dd25b82-e18f-11e7-8431-09877f55718d.jpg)
![2](https://user-images.githubusercontent.com/20511534/34029541-225857a6-e18f-11e7-881d-c07dee46b156.jpg)

Can you please help us with this issue.?

Thanks.

**Comment by adamfisher** [comment] 2017-12-17 02:46
Duplicate of #3 - there is some code that may help with this in that issue, otherwise you could also try wrapping the player in other Xamarin Forms layouts sort of like how this video is stretched to the entire edge of the page:

```
<RelativeLayout x:Name="MainMenuLayout">
    <o:VideoPlayer x:Name="VideoPlayer" Source="{me:VideoResource snow.mp4}"
		  DisplayControls="False" AutoPlay="True" Repeat="True" Volume="0" FillMode="ResizeAspectFill"
		  RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width}"
		  RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height}" />
</RelativeLayout>
```

**Closed as completed by adamfisher** 2017-12-17 02:46 UTC
Labels: VideoPlayer.Android

**Comment by SudharsanKrishnamoorthy** [comment] 2017-12-18 09:14
Hi Adam,
   We have tried after modifying the code as you mentioned above. 

 layout = new RelativeLayout();
            layout.Children.Add(videoPlayer,
                Constraint.RelativeToParent((Parent) =>videoPlayer.X),
                Constraint.RelativeToParent((Parent) => videoPlayer.Y),
                Constraint.RelativeToParent((Parent) => Parent.Width),
                Constraint.RelativeToParent((Parent) => Parent.Height)
                );

We also tried this: 
Resize
ResizeAspect
ResizeAspectFill

Still we cant resolve this in moto g 2nd gen.. Please understand the issue, that the video player is working as expected in all the device except **" Moto g 2nd gen"**. 

Please find the screenshots after modifying the changes. (Realative layout).
1. It is working fine as expected while loading the video until it the orientation changes.
2. Once the device changes the orientation the video gets displayed in half as seen below.
![screenshot_2017-12-18-14-32-04](https://user-images.githubusercontent.com/20511534/34098167-802f20e8-e401-11e7-8436-fa10606b8e07.png)
![screenshot_2017-12-18-14-32-14](https://user-images.githubusercontent.com/20511534/34098168-80610d7e-e401-11e7-848e-7bd78ecc0594.png)
![screenshot_2017-12-18-14-32-24](https://user-images.githubusercontent.com/20511534/34098169-80928a66-e401-11e7-9f39-dcc9ce5d7239.png)
![screenshot_2017-12-18-14-32-29](https://user-images.githubusercontent.com/20511534/34098170-80c449de-e401-11e7-9ad0-7c91437cfb23.png)

Please help us on this issue.

Thanks in advance.
