### ISSUE TITLE
video issue in home button pressed

### ISSUE THREAD

**Issue by cdamose** [adamfisher/Xamarin.Forms.VideoPlayer#14] opened 2017-03-24 14:10 UTC
Hi,

I have purchased CHILL PLAYER  in the identifier of  "com.tranzuara.all".

On Video is playing, while pressing the home button, video has been completed in background. When again enter into the app video is completed.  

The solution which was given you is not working,

I need the solution be like, while pressing home button,the video should be paused and resume while entering into the app.

Please try to be provide the solution ASAP.

Thanks,
Amose

**Comment by adamfisher** [comment] 2017-03-24 16:07
Duplicate of #6. Please continue to comment there instead of here. I will update that issue with my comments.

**Closed as completed by adamfisher** 2017-03-24 16:07 UTC
Labels: duplicate, VideoPlayer.Android
