### ISSUE TITLE
Can't install anymore

### ISSUE THREAD

**Issue by mwallon** [adamfisher/Xamarin.Forms.VideoPlayer#116] opened 2018-04-21 08:59 UTC
After using this for a while without problems I suddenly get this error when I try to istall or update, can someone help me?
/magnus

"Could not install package 'Octane.Xam.VideoPlayer 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by adamfisher** [comment] 2018-04-22 20:05
Duplicate of #91

**Closed as completed by adamfisher** 2018-04-22 20:05 UTC
Labels: duplicate, question
