### ISSUE TITLE
On Android Platform Full Screen Button

### ISSUE THREAD

**Issue by ercev** [adamfisher/Xamarin.Forms.VideoPlayer#140] opened 2018-09-05 10:50 UTC
Hi,

there is no full screen button in android project. there is only play-pause , rewind and forward. i try to add display controls but didn't work. so i can't make it full screen on android. iOS is ok. with the same code.

`   <o:VideoPlayer Grid.Row="0" 
                               HorizontalOptions="FillAndExpand" 
                               VerticalOptions="FillAndExpand" 
                               DisplayControls="true"
                               x:Name="livePlayer"/>`

**Comment by adamfisher** [comment] 2018-09-08 20:40
Duplicate of #37

**Closed as completed by adamfisher** 2018-09-08 20:40 UTC
Labels: duplicate, question, VideoPlayer.Android
