### ISSUE TITLE
App Center build for UWP fails if video player is included

### ISSUE THREAD

**Issue by hauteur** [adamfisher/Xamarin.Forms.VideoPlayer#123] opened 2018-05-25 12:27 UTC
Not getting any response whatsoever on issue #99, so I thought I'd try creating a new one.  

This is completely related to issues #99 - UWP could not load library and #121 -FileNotFoundException in UWP.   This gives a similar error, but not exactly the same:

System.IO.FileNotFoundException: 'Could not load file or assembly 'Octane.Xamarin.Forms.VideoPlayer, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. **The system cannot find the file specified.'**

This is not, as far as I can tell, a simple binding redirect fix.  Just including the library in your solution causes the App Center build to fail.  Take it out, and it works.  Put it in, and it fails.  There are no warnings or errors in Visual Studio until you reference anything with the player.

Also - The provided ChillPlayer sample has the same issue.  All you have to do to reproduce is pull it down and try to run it.

**Comment by adamfisher** [comment] 2018-05-27 16:32
Thank you for specifying it is a duplicate of #99. It is easier to track everything on one thread so I will be providing updates on that issue.

**Closed as completed by adamfisher** 2018-05-27 16:32 UTC
Labels: duplicate, VideoPlayer.UWP
