### ISSUE TITLE
Cannot update VideoPlayer

### ISSUE THREAD

**Issue by dhrubha** [adamfisher/Xamarin.Forms.VideoPlayer#112] opened 2018-03-22 21:05 UTC
I am working on a PCL project in Visual Studio 2015. This project ran fine previously. However, when I try to update VideoPlayer to v2.0.1 through the NuGet Package Manager I receive the following message:

Error		Could not install package 'Octane.Xam.VideoPlayer 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

This is the first I have heard of Profile versions and I'm not clear on what should be changed.

**Comment by scastria** [comment] 2018-03-22 22:18
There are many PCL profiles to choose from depending on your needs.  If you just need Android and iOS support, then you have a few other PCL profiles you can switch to which this component might work with.  Go into the project settings for your PCL project and try changing the PCL profile number to something else, like Profile78, Profile136, etc.  I am not sure which profiles this component is compatible with so you will have to do trial and error.

**Comment by dhrubha** [comment] 2018-03-23 01:19
Thanks very much.

I should have found this list of PCL profiles earlier, but it is here for anyone else who needs it:

http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html

**Comment by adamfisher** [comment] 2018-03-23 20:13
Duplicate of #91

**Closed as completed by adamfisher** 2018-03-23 20:13 UTC
Labels: duplicate
