### ISSUE TITLE
Upgrading nuget to 2.1.0 gives incompatible message

### ISSUE THREAD

**Issue by pdougla002** [adamfisher/Xamarin.Forms.VideoPlayer#93] opened 2018-01-24 03:23 UTC
Hi Adam, I get this when trying to install the latest nuget.
Could not install package 'Octane.Xam.VideoPlayer 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. Thanks, if you have any advice. PD

**Comment by adamfisher** [comment] 2018-01-24 20:20
Duplicate of #91

**Closed as completed by adamfisher** 2018-01-24 20:20 UTC
Labels: duplicate, question

**Comment by pdougla002** [comment] 2018-01-24 23:44
Perfecto, I figured. Thank you
