### ISSUE TITLE
ChillPlayer sample doesn't compile on iOS

### ISSUE THREAD

**Issue by scastria** [adamfisher/Xamarin.Forms.VideoPlayer#107] opened 2018-03-22 15:27 UTC
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error:   Bundle Resource 'Icon-60@3x.png' not found on disk (should be at '/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.iOS/Resources/Icon-60@3x.png') (ChillPlayer.iOS)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error:   Bundle Resource 'Icon-Small-40@3x.png' not found on disk (should be at '/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.iOS/Resources/Icon-Small-40@3x.png') (ChillPlayer.iOS)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error:   Bundle Resource 'Icon-Small@3x.png' not found on disk (should be at '/GIT/Xamarin.Forms.VideoPlayer/ChillPlayer/ChillPlayer.iOS/Resources/Icon-Small@3x.png') (ChillPlayer.iOS)

**Comment by adamfisher** [comment] 2018-04-22 22:31
Duplicate of #109 and will be tracked there.

**Closed as completed by adamfisher** 2018-04-22 22:31 UTC
Labels: bug, Chill Player

**Comment by adamfisher** [comment] 2018-04-22 22:34
This issue should be resolved now with the latest commit.
