### ISSUE TITLE
aspect ratio not right on android.

### ISSUE THREAD

**Issue by bmanners** [adamfisher/Xamarin.Forms.VideoPlayer#44] opened 2017-06-26 07:17 UTC
I could be doing something wrong but the aspect ratio is being stretched on Android. I have FillMode="ResizeAspect" but regardless of the FillMode setting the video is still stretched.?

**Comment by adamfisher** [comment] 2017-06-27 03:54
Duplicate of #3

**Closed as completed by adamfisher** 2017-06-27 03:54 UTC
Labels: VideoPlayer.Android
