### ISSUE TITLE
Video player not working in Release mode UWP

### ISSUE THREAD

**Issue by pizzahead24** [adamfisher/Xamarin.Forms.VideoPlayer#153] opened 2018-12-10 17:52 UTC
Right now the player works when ran locally on all platforms. It also works for Android and iOS in production, however it doesn't load on UWP in production. There are no exceptions thrown or anything, it just is a blank space with no player.

**Comment by pizzahead24** [comment] 2018-12-10 17:55
Just a note, we recently updated our app from Xamarin Forms 2.5 to Forms 3.3. When we updated our app we also updated the component to the latest release of the octane player.

**Comment by adamfisher** [comment] 2018-12-12 02:36
duplicate of #137

**Closed as completed by adamfisher** 2018-12-12 02:36 UTC
Labels: duplicate, VideoPlayer.UWP

**Comment by nitrouscutter** [comment] 2019-03-13 13:00
@adamfisher Why did you close this? We have a demo of our app today and had to install the Xamarin app debug version because the video player won't work in release mode in UWP. Is this not fixable?
