### ISSUE TITLE
Enhancement: exoplayer for Android

### ISSUE THREAD

**Issue by fmeneuhe** [adamfisher/Xamarin.Forms.VideoPlayer#38] opened 2017-06-21 19:12 UTC
Hi,
Just one suggestion: include the Google Exoplayer lib for Android. 
Thanks

**Comment by adamfisher** [comment] 2017-06-23 14:51
Duplicate of https://github.com/adamfisher/Xamarin.Forms.VideoPlayer/issues/29

**Closed as completed** 2017-06-23 14:51 UTC
Labels: duplicate, enhancement
